version: '3.3'

services:
  webapp:
    image: cesconetto/python-test
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:8080"
    networks:
      - appnet
networks:
  appnet:
    driver: overlay